#!/bin/sh
### BEGIN INIT INFO
# Provides:          kvideocaptured
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Provides videostream from videodevice to network clients
# Description:       Gets frames from videodevice file and provides them 
#                    as a videostream to network clients using
#                    MJPEG or FLV over HTTP protocols.
### END INIT INFO

set -e

KVCAP=/usr/sbin/kvideocaptured

# Check for daemon presence
[ -x "$KVCAP" ] || exit 0

OPTIONS="-d"

# Get lsb functions
. /lib/lsb/init-functions

set +e

case "$1" in
  start)
    log_daemon_msg "Starting capture service" "kvideocaptured"
    start-stop-daemon --start --quiet --oknodo --exec "$KVCAP" -- $OPTIONS
    log_end_msg $?
    ;;
  stop)
    log_daemon_msg "Stopping capture service" "kvideocaptured"
    start-stop-daemon --stop --quiet --oknodo --retry 2 --exec "$KVCAP"
    log_end_msg $?
    ;;
  restart)
    $0 stop
    sleep 1    
    $0 start
    ;;
  reload|force-reload)
    log_daemon_msg "Reloading capture service" "kvideocaptured"
    start-stop-daemon --stop --signal 1 --exec "$KVCAP"
    log_end_msg $?
    ;;
  status)
    status_of_proc "$KVCAP" kvideocaptured
    ;;
  *)
    log_success_msg "Usage: /etc/init.d/kvideocapture {start|stop|restart|reload|force-reload|status}"
    exit 1
esac
